feat(interface): 添加返回值类型
tuya/tuya-panel-sdk pull request #34
Opened 2021-05-21 07:34 UTC by Saber2pr

feat(interface): 补充commonApi类型提示

feat(laserbitmaptoimagebase64): 补充返回值类型

docs(readme): 修订文档地址

2021-05-21 07:55 UTC, ShinyLeee requested changes

2021-05-21 07:55 UTC, ShinyLeee commented on packages/tuya-panel-api/src/common/device.ts
>   * @param {string} gwId 设备Id
建议增加上 @docs 链接地址

2021-05-21 08:59 UTC, Saber2pr commented on packages/tuya-panel-api/src/common/device.ts
>   * @param {string} gwId 设备Id
加上了

2021-05-21 09:22 UTC, ShinyLeee approved these changes
LGTM~

2021-06-25 08:18 UTC, youngjuning approved these changes
LGTM

2021-06-25 08:21 UTC, merged