Feature/tuya panel gateway sdk
tuya/tuya-panel-sdk pull request #42
Opened 2021-06-21 06:03 UTC by Oliverzzq

## Description

Universal gateway control business component
1.AddDeviceTip
2.SetPassword
3.TempHumWithBlur
4.TopBarWithArc

## Package

- [ ] tuya-panel-animation-sdk
- [ ] tuya-panel-api
- [ ] tuya-panel-electrician-sdk
- [ ] tuya-panel-ipc-sdk
- [ ] tuya-panel-lamp-sdk
- [ ] tuya-panel-lock-sdk
- [ ] tuya-panel-robot-sdk
- [x] tuya-panel-gateway-sdk

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-06-25 11:00 UTC, youngjuning commented on package.json
> -    "version:pre": "yarn build && lerna version --canary --yes --pre-dist-tag=rc --preid=rc",
这里不需要改，提升版本和发布是分开的

2021-06-25 11:08 UTC, youngjuning requested changes

2021-06-25 11:08 UTC, youngjuning commented on package.json
> -    "version:prepatch": "yarn build && lerna version --canary patch --yes --pre-dist-tag=rc --preid=rc",
这里不要改动

2021-06-25 11:09 UTC, youngjuning commented
@Oliverzzq 大佬，看下需要改的地方

2021-06-28 02:16 UTC, youngjuning approved these changes
LGTM~

2021-06-28 10:51 UTC, ShinyLeee commented on packages/tuya-panel-gateway-sdk/src/components/addDeviceTip/i18n/index.ts
> +Strings.applyStrings(LocalStrings);
独立实例化一个 I18N，建议不要复用 components 的 Strings，key 可能会重复

2021-06-28 10:51 UTC, ShinyLeee commented on packages/tuya-panel-gateway-sdk/src/components/setPassword/i18n/index.ts
> +Strings.applyStrings(LocalStrings);
独立实例化一个 I18N，建议不要复用 components 的 Strings，key 可能会重复

2021-06-29 07:46 UTC, ShinyLeee approved these changes

2021-06-29 07:50 UTC, merged