feat: lock dete-picker-view component add
tuya/tuya-panel-sdk pull request #53
Opened 2021-07-09 03:56 UTC by youngjuning

## Description

lock dete-picker-view component add

## Package

- [x] tuya-panel-lock-sdk

## Type of change

Please select the relevant option.
- [x ] New feature (non-breaking change which adds functionality)

2021-07-09 04:19 UTC, youngjuning commented
LGTM~

2021-07-12 06:30 UTC, ShinyLeee commented on packages/tuya-panel-lock-sdk/src/date-picker-view/interfance.ts
> +import { StyleProp, ViewStyle, ColorPropType, ImageStyle } from 'react-native';
文件名错的,interface.ts 吧

2021-07-12 06:30 UTC, ShinyLeee requested changes
文件名修改下

2021-07-12 13:39 UTC, zegezs commented on packages/tuya-panel-lock-sdk/src/date-picker-view/interfance.ts
> +import { StyleProp, ViewStyle, ColorPropType, ImageStyle } from 'react-native';
> 文件名错的,interface.ts 吧

2021-07-12 13:39 UTC, zegezs commented on packages/tuya-panel-lock-sdk/src/date-picker-view/interfance.ts
> +import { StyleProp, ViewStyle, ColorPropType, ImageStyle } from 'react-native';
> 文件名错的,interface.ts 吧

已经修复

2021-07-13 02:09 UTC, ShinyLeee requested changes

2021-07-13 02:09 UTC, ShinyLeee commented on packages/tuya-panel-lock-sdk/src/date-picker-view/i18n/strings.ts
> +    placeholderTip: 'Please select date',
多语言 key 命名不规范

2021-07-13 08:09 UTC, zegezs commented on packages/tuya-panel-lock-sdk/src/date-picker-view/i18n/strings.ts
> +    placeholderTip: 'Please select date',
已改

2021-07-13 08:44 UTC, youngjuning commented
LGTM

2021-07-13 08:50 UTC, ShinyLeee approved these changes
LGTM

2021-07-14 06:31 UTC, merged