Feature/tuya panel outdoor sdk
tuya/tuya-panel-sdk pull request #58
Opened 2021-07-15 01:48 UTC by qinglizhang

## Description

Please provide a brief summary of the changes. If it is related to an issue, please bring the issue number, like `fixes #${number}`.

## Package

- [ ] tuya-panel-animation-sdk
- [ ] tuya-panel-api
- [ ] tuya-panel-electrician-sdk
- [ ] tuya-panel-ipc-sdk
- [ ] tuya-panel-lamp-sdk
- [ ] tuya-panel-lock-sdk
- [ ] tuya-panel-robot-sdk

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-07-31 03:04 UTC, youngjuning commented
index.d.ts 为啥是空的？

2021-07-31 03:35 UTC, youngjuning commented
@qinglizhang 处理一下 yarn.lock 的冲突

2021-07-31 03:35 UTC, youngjuning commented on packages/tuya-panel-outdoor-sdk/src/components/setting-slider/index.tsx
> +  onValueConfrim: (backValue: string | number) => void;
onValueConfrim -> onValueConfirm

2021-07-31 03:35 UTC, youngjuning commented on packages/tuya-panel-outdoor-sdk/src/components/setting-slider/index.tsx
> +  onValueConfrim,
onValueConfrim -> onValueConfirm

2021-07-31 06:06 UTC, qinglizhang commented on example/src/config/routers.js
> +// import LampCategory from '../scenes/Lamp';
没有调用的地方 所以注释了

2021-08-03 06:16 UTC, ShinyLeee commented on packages/tuya-panel-outdoor-sdk/src/components/location-text/i18n/string.tsx
> +    unknownLocation: 'Unknown Location',
多语言不规范，组件库里尽量不要糅合多语言，尽量让业务侧传递

2021-08-03 06:17 UTC, ShinyLeee commented on packages/tuya-panel-outdoor-sdk/src/components/location-text/index.tsx
> +const defaultText = Strings.getLang('unknownLocation');
defaultText 让业务侧传过来吧，不要写在组件库里了

2021-08-03 06:18 UTC, ShinyLeee commented on packages/tuya-panel-outdoor-sdk/src/components/setting-slider/index.tsx
> +  const [titles, setTitles] = useState({ startTxt: '', endTxt: '', valueTxt: '' });
同样的，多语言尽量不要在组件这层写

2021-08-03 06:18 UTC, ShinyLeee commented on example/src/config/routers.js
> +// import LampInfo from '../../../packages/tuya-panel-lamp-sdk/package.json';
为什么有改动到其他 sdk 的文件

2021-08-03 06:19 UTC, ShinyLeee requested changes
主要是多语言问题

2021-08-04 01:53 UTC, youngjuning approved these changes
LGTM~

2021-08-04 01:53 UTC, merged