feat: add progess unlockButton barpercent scrollRuler component
tuya/tuya-panel-sdk pull request #67
Opened 2021-08-02 02:42 UTC by baohuse

## Owner

- [ ] Nickname(Tuya): 

## Description

Initialize the health sdk and add 6 components and examples
barPercent
progess
scrollRuler
unLockButton
Add a hook
useCountDown

## Package

- [ ] tuya-panel-animation-sdk
- [ ] tuya-panel-api
- [ ] tuya-panel-electrician-sdk
- [ ] tuya-panel-ipc-sdk
- [ ] tuya-panel-lamp-sdk
- [ ] tuya-panel-lock-sdk
- [ ] tuya-panel-robot-sdk
- [ ] tuya-panel-outdoor-sdk
- [x] tuya-panel-health-sdk

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-08-02 06:49 UTC, youngjuning commented
@baohuse 单测跑失败了，看一下

2021-08-04 03:16 UTC, youngjuning commented
@baohuse 麻烦处理一下 package.json 的冲突

2021-08-09 06:24 UTC, baohuse commented
@youngjuning 已处理

2021-08-12 06:28 UTC, youngjuning requested changes

2021-08-12 06:28 UTC, youngjuning commented on example/src/scenes/Health/CountDown/index.js
> +    dsc_default: 'Default',
@baohuse @ShinyLeee 这个应该是要符合规范的把

2021-08-12 06:28 UTC, youngjuning commented on example/src/scenes/Health/Progess/index.js
> +    dsc_default: 'Default',
@baohuse @ShinyLeee 这个应该是要符合规范的把

2021-08-12 06:28 UTC, youngjuning commented on example/src/scenes/Health/ScrollRuler/index.js
> +  en: {
@baohuse @ShinyLeee 这个应该是要符合规范的把

2021-08-12 06:28 UTC, youngjuning commented on example/src/scenes/Health/SleepBarPercent/index.js
> +  en: {
@baohuse @ShinyLeee 这个应该是要符合规范的把

2021-08-12 06:28 UTC, youngjuning commented on example/src/scenes/Health/UnlockButton/index.js
> +  en: {
@baohuse @ShinyLeee 这个应该是要符合规范的吧

2021-08-12 07:24 UTC, youngjuning commented on packages/tuya-panel-health-sdk/src/components/barPercent/BarList.tsx
> +export const Item: SFC<ItemProps> = (props: ItemProps) => {
SFC 被弃用了，建议改成 FunctionComponent

2021-08-12 08:13 UTC, youngjuning approved these changes
LGTM~

2021-08-12 08:13 UTC, merged