Add TYIpcDragSort component
tuya/tuya-panel-sdk pull request #69
Opened 2021-08-06 02:16 UTC by HeLiangYu

## Owner

- [√] Nickname(Tuya): 伽拉

## Description

tuya-panel-ipc-sdk add TYIpcDragSort component.

## Package

- [√] tuya-panel-ipc-sdk

## Type of change

Please select the relevant option.

- [√] New feature (non-breaking change which adds functionality)

2021-08-06 03:50 UTC, youngjuning requested changes
@HeLiangYu 麻烦 commit 记录 rebase 一下

2021-08-06 10:37 UTC, HeLiangYu commented
Add TYIpcDragSort Component

2021-08-06 10:39 UTC, HeLiangYu commented
4ee38b153b84c4a7089890c26ace4ad8ef6373ca 
Add TYIpcDragSort Component

2021-08-12 03:47 UTC, youngjuning requested changes

2021-08-12 03:50 UTC, youngjuning requested changes

2021-08-12 03:50 UTC, youngjuning commented on packages/tuya-panel-ipc-sdk/src/ty-ipc-drag-sort/dragSort.tsx
> +const DragSort: React.FC<TYIpcDragSortProps> & {
React.FC 被遗弃了已经，推荐使用 React.FunctionComponent

2021-08-12 04:22 UTC, youngjuning commented on packages/tuya-panel-ipc-sdk/src/ty-ipc-drag-sort/dragSort.tsx
> +const DragSort: React.FC<TYIpcDragSortProps> & {
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

2021-08-12 08:10 UTC, youngjuning approved these changes
LGTM

2021-08-12 08:11 UTC, merged